apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    env  : prod
    owner: Dasha
spec:
  selector:
    project: {{ .Release.Name }}    # Selecting PODS with those Labels
  ports:
    - name      : {{ .Release.Name }}-listener
      protocol  : TCP
      port      : 3000  # Port on Load Balancer
      targetPort: 3000  # Port on POD
  type: LoadBalancer